library(shinydashboard)
source("data.R")

ui <- dashboardPage(
  dashboardHeader(title = "ELNs Study"),
  dashboardSidebar(sidebarMenu(
    menuItem("Introduction", tabName = "intro", icon = icon("archive")),
    menuItem("Survey", tabName = "survey",icon = icon("laptop")),
    menuItem("Grade", tabName = "grades",icon = icon("table"))
    
  )),
  
  #define the body of the app
  dashboardBody(
    tabItems(
      #First tab content
      tabItem(tabName = "intro",
              fluidRow(
                column(12,
                       #Description of app
                       h1("Introduction"),
                       box(background = "blue", width = 12,
                           h4("Academic teaching laboratory courses have emphasized the importance of accurate record keeping and extensively trained students in good documentation practices based on paper lab notebooks (PLNs).Though the use of PLNs has been perfected over several decades, the large data generated by many biology science experiments are better managed through electronic laboratory notebooks
(ELNs). Traditionally in those science laboratory courses, students use paper notebooks to take notes, record observation data, take pictures or plot results. The advantages of using ELNs is obvious. They are less time consuming, more organized, easy to access and easy to embed images. Moreover, ELNs can simplify data processing, provide quick analysis result, and share the results with other users conveniently. 
                              ")),#end of box
                       br(),
                       box(background = "blue", width = 12,
                           h4("There are two objectives in this study about electronic laboratory notebooks. One is to find out whether the ELNs format improves students’ grades. The other is to evaluate the effectiveness of ELNs on improving the quality of their students’ study. "))#end of box
                       
                )#end of column
                           )#end of fluidrow
                           ),#end of tabitem 1
      tabItem(tabName = "survey",
              fluidRow(
                column(3,
                       uiOutput("title1"),
                       selectizeInput("term", "Year and Term:", selected = "2016 Fall",choices = levels(data$Term)),
                       br(),
                       selectizeInput("question", "Question:", choices = colnames(data[1:12])),
                       br()
                ), #end of column
                column(9,
                       fluidRow(
                         plotOutput("survey_question", height = 500)
                       )#end of fluidrow
                )#end of column


              )#endo of fluid Row
      ), #end of tabitem 2
       tabItem(tabName = "grades",
               fluidRow(
                 column(12,
                        fluidRow(
                          plotOutput("grade", height = 500)
                        )#end of fluidrow
                 )#end of column
               )#end of fluid Row
       ) #end of tabitem 3
      )#ent of all tabitems
    )#end of dashboard body
  
  )#end of dashboard page



